### ISSUE TITLE
Grid css

### ISSUE THREAD

**Issue by aripinsuantoro** [ahmadfaqih796/learning-css#1]
I'm still confused about the display grid, how do I implement the display grid?

**Comment by ahmadfaqih796** [comment]
In simple terms, CSS Grid is CSS that can divide columns on a website into the desired sections, both horizontally and vertically. The use of CSS Grid aims to make it easier for developers to create layouts from designs that have been made.

**Comment by ahmadfaqih796** [comment]
> I'm still confused about the display grid, how do I implement the display grid?

In simple terms, CSS Grid is CSS that can divide columns on a website into the desired sections, both horizontally and vertically. The use of CSS Grid aims to make it easier for developers to create layouts from designs that have been made.

**Comment by aripinsuantoro** [comment]
> > I'm still confused about the display grid, how do I implement the display grid?
> 
> In simple terms, CSS Grid is CSS that can divide columns on a website into the desired sections, both horizontally and vertically. The use of CSS Grid aims to make it easier for developers to create layouts from designs that have been made.

ok thanks u, sir

**Comment by ahmadfaqih796** [comment]
In simple terms, CSS Grid is CSS that can divide columns on a website into the desired sections, both horizontally and vertically. The use of CSS Grid aims to make it easier for developers to create layouts from designs that have been made.
