### ISSUE TITLE
image does not appear

### ISSUE THREAD

**Issue by aripinsuantoro** [ahmadfaqih796/learning-css#2]
how do the images appear on the screen? please help

**Comment by ahmadfaqih796** [comment]
> how do the images appear on the screen? please help

We can add images in HTML by using the <img> tag. This tag has a mandatory attribute, which is src . If we do not fill in the src attribute, then the image will not be displayed. The image URL address in the src attribute can be either a URL or a path address. Then the <img> tag must be closed by adding a slash.
